janus-vip:
  image: rancher/load-balancer-service
  ports:
  # HTTPS mandatory for webRTC!
  - "${public_port}:443"
  links:
  - janus
  external_links:
  labels:
    io.rancher.loadbalancer.target.janus: ${domain_name}:${public_port}/janus=8088
    io.rancher.loadbalancer.target.janus: ${domain_name}:${public_port}/jangouts=8080
janus:
  image: qxip/docker-jangouts
  ports:
  - "7889:7889"
  - "7089:7089"
  - "8089:8089"
  - "7088:7088"
  - "8088:8088"
  - "8000:8000"
  - "8080:8080"
  - "10000-10200:10000-10200/udp"
  restart: always
  tty: true
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
  - DOMAIN_NAME: ${domain_name}
  - PUBLIC_PORT: ${public_port}
