.catalog:
  name: "Jangouts"
  version: "0.2.3-rancher1"
  description: "Jangouts (Janus Hangouts)"
  maintainer: "Lorenzo Mangani <lorenzo.mangani@gmail.com>"
  uuid: janus-0
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Service"
      type: "int"
      default: 8080
      required: true
  questions:
    - variable: "domain_name"
      label: "External Domain Name"
      description: "Domain Name for Service"
      type: "string"
      default: ""
      required: true
