name: elassandra
version: 5.5.0
appVersion: 5.5.0
icon: https://github.com/strapdata/elassandra/raw/v5.5.0-strapdata/elassandra-logo.png
description: Elassandra = Elasticsearch + Cassandra
  Apache Cassandra is a free and open-source distributed database management
  system designed to handle large amounts of data across many commodity servers, providing
  high availability with no single point of failure.
keywords:
- cassandra
- elassandra
- database
- nosql
home: http://www.strapdata.com
maintainers:
- name: qxip
  email: info@qxip.net
engine: gotpl
