apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sentinl
  labels:
    app: {{ template "efk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kibana.yml: |
    # Injected Kibana config from HELM
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{ template "efk.elasticsearch.url" . }}
    sentinl:
      settings:
        email:
          active: {{ template "efk.sentinl.email.active" . }}
          user: {{ template "efk.sentinl.email.smtp_user" . }}
          password: {{ template "efk.sentinl.email.smtp_pass" . }}
          host: {{ template "efk.sentinl.email.smtp_server" . }}
          ssl: {{ template "efk.sentinl.email.ssl" . }}
        report:
          active: {{ template "efk.sentinl.report.active" . }}
          tmp_path: /tmp/
