apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sentinl
  labels:
    app: {{ template "esk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kibana.yml: |
    # Injected Kibana config from HELM
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{ template "esk.elasticsearch.url" . }}
    sentinl:
      settings:
        email:
          active: {{ default "false" .Values.sentinl.email.active }}
          user: {{ default "username" .Values.sentinl.email.smtp_user" }}
          password: {{ default "password" .Values.sentinl.email.email.smtp_pass" }}
          host: {{ default "localhost" .Values.sentinl.email.smtp_server" }}
          ssl: {{ default "false" .Values.sentinl.email.email.ssl" }}
        report:
          active: {{ default "true" .Values.sentinl.email.active" }}
          tmp_path: /tmp/
