apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sentinl
  labels:
    app: {{ template "esk.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kibana.yml: |
    # Injected Kibana config from HELM
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{ template "esk.elasticsearch.url" . }}
    vega.enableExternalUrls: false
    sentinl:
      settings:
        email:
          active: {{ .Values.sentinl.email.active }}
          user: {{ .Values.sentinl.email.smtp_user }}
          password: {{ .Values.sentinl.email.smtp_pass }}
          host: {{ .Values.sentinl.email.smtp_server }}
          ssl: {{ .Values.sentinl.email.ssl }}
        report:
          active: {{ .Values.sentinl.report.active }}
          # executable_path=chrome
