.catalog:
  name: "Homer"
  version: "5.0.5-rancher1"
  description: "Homer: VoIP Monitoring & Capture"
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for WebApp"
      type: "int"
      default: 8080
      required: true
    - variable: "hep_port"
      label: "Public HEP Port"
      description: "Unique public HEP port for Kamailio"
      type: "int"
      default: 9060
      required: true
    - variable: "DB_USER"
      label: "DB User"
      description: "DB Username"
      type: "string"
      default: "homer_user"
      required: true
    - variable: "DB_PASS"
      label: "DB Password"
      description: "DB Password"
      type: "string"
      default: "homer_password"
      required: true
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "DB Root Password"
      description: "MYSQL_ROOT_PASSWORD"
      type: "string"
      default: "secret"
      required: true
    - variable: "USE_REMOTE_MYSQL"
      label: "Use Remote MySQL (true/false)"
      description: "USE_REMOTE_MYSQL"
      type: "string"
      default: "false"
      required: true
      
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "homer"
        upstream_port: 8080
