apiVersion: v1
description: Elasticsearch visualization platform
name: kibana
version: 6.2.4
icon: https://static-www.elastic.co/assets/bltf11265439e44d327/logo-elastic-kibana-lt.svg?q=890
sources:
  - https://www.elastic.co/products/kibana
