{{- if .Values.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.fullname" . }}
type: Opaque
data:
{{- range $key, $value := .Values.tls.files }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end -}}