apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: heplify-server
    name: heplify-server
  spec:
    ports:
    - name: "9060"
      port: 9060
      targetPort: 9060
    - name: 9060-udp
      port: 9060
      protocol: UDP
      targetPort: 9060
    - name: "9096"
      port: 9096
      targetPort: 9096
    selector:
      io.kompose.service: heplify-server
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telegraf
    name: telegraf
  spec:
    ports:
    - name: "8092"
      port: 8092
      protocol: UDP
      targetPort: 8092
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
    selector:
      io.kompose.service: telegraf
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: homer-webapp
    name: homer-webapp
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      io.kompose.service: homer-webapp
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      io.kompose.service: db
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telestats
    name: telestats
  spec:
    ports:
    - name: "8094"
      port: 8094
      protocol: UDP
      targetPort: 8094
    selector:
      io.kompose.service: telestats
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
      spec:
        containers:
        - env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_ROOT_HOST
            value: '%'
          - name: MYSQL_ROOT_PASSWORD
          image: mariadb:latest
          name: db
          resources: {}
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: heplify-server
    name: heplify-server
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: heplify-server
      spec:
        containers:
        - args:
          - ./heplify-server
          env:
          - name: HEPLIFYSERVER_DBADDR
            value: db:3306
          - name: HEPLIFYSERVER_DBDRIVER
            value: mysql
          - name: HEPLIFYSERVER_DBPASS
          - name: HEPLIFYSERVER_DBUSER
            value: root
          - name: HEPLIFYSERVER_HEPADDR
            value: 0.0.0.0:9060
          - name: HEPLIFYSERVER_LOGLVL
            value: info
          - name: HEPLIFYSERVER_LOGSTD
            value: "true"
          - name: HEPLIFYSERVER_PROMADDR
            value: 0.0.0.0:9096
          - name: HEPLIFYSERVER_PROMTARGETIP
          - name: HEPLIFYSERVER_PROMTARGETNAME
          image: negbie/heplify-server:latest
          name: heplify-server
          ports:
          - containerPort: 9060
            hostPort: 9060
            protocol: UDP
          - containerPort: 9060
            hostPort: 9060
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: homer-webapp
    name: homer-webapp
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: homer-webapp
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: db
          - name: DB_PASS
          - name: DB_USER
            value: root
          image: sipcapture/homer-webapp
          name: homer-webapp
          resources: {}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webapp-config-volume
              mountPath: /homer-semaphore
        volumes:
          - name: webapp-config-volume
            configMap:
              name: homer-webapp-config 
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telegraf
    name: telegraf
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: telegraf
      spec:
        containers:
        - image: telegraf:1.5-alpine
          name: telegraf
          ports:
          - containerPort: 8092
            protocol: UDP
          - containerPort: 8125
            protocol: UDP
          resources: {}
          volumeMounts:
           - name: telegraf-config-volume
             mountPath: /etc/telegraf
        volumes:
          - name: telegraf-config-volume
            configMap:
              name: homer-telegraf-config
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telestats
    name: telestats
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: telestats
      spec:
        containers:
        - image: qxip/telestats:master
          name: telestats
          ports:
          - containerPort: 8094
            protocol: UDP
          resources: {}
          volumeMounts:
           - name: telestats-config-volume
             mountPath: /
        volumes:
          - name: telestats-config-volume
            configMap:
              name: homer-telestats-config
  status: {}
kind: List
metadata: {}
