apiVersion: v1
data:
  /config.js: |
    {
     "id" : "HEPLIFY-stats-001",
     "socket": "udp",
     "port": 8094,
     "address": "0.0.0.0",
     "mysql": {
       "debug": false,
       "dbOpts": {
         "host": "db",
         "user": "homer_user",
         "password": "homer_password",
         "database": "homer_statistic"
       },
       "maxRows": 1000
     },
     "stats" : {
        "data" : false,
        "method" : true,
        "gauge" : "gauge_count", // _count, _max, _mean, _min
        "counter" : "counter_count" // _count, _max, _mean, _min
     },
     "debug": true
    }
kind: ConfigMap
metadata:
  name: homer-telestats-config
