.catalog:
  name: "Etcd"
  version: "2.3.0-rancher1"
  minimum_rancher_version: v1.1.1
  maximum_rancher_version: v1.1.4
  description: |
    Distributed highly-available key-value store
  minimum_rancher_version: "v0.46.0"
  questions:
    - variable: "REPLICAS"
      description: "Number of Etcd nodes. 3, 5, or 7 are good choices"
      label: "Number of Nodes:"
      required: true
      default: 3
      type: "int"
etcd:
  retain_ip: true
  scale: ${REPLICAS}
