elassandra:
  restart: always
  image: strapdata/elassandra
  volumes_from:
    elassandra-volume
  ports:
    "${public_port}:9200"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: elassandra-volume
elassandra-volume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /var/lib/cassandra
    - /var/log/cassandra
  volume_driver: "${volume_driver}"
  entrypoint: /bin/true
  image: busybox
