.catalog:
  name: "Elassandra"
  version: "5.5.0.10-rancher1"
  description: "Strapdata Elassandra"
  maintainer: "Lorenzo Mangani <lorenzo.mangani@gmail.com>"
  uuid: elassandra-5
  questions:
    - variable: "cassandra_dc"
      description: "DC Name (no spaces)"
      label: "Cluster DC:"
      required: true
      default: "ranch-elassandra-01"
      type: "string"
    - variable: "cassandra_rack"
      description: "Rack Name (no spaces)"
      label: "Cluster Rack:"
      required: true
      default: "rack1"
      type: "string"
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for ES API"
      type: "int"
      default: 9200
      required: true
    - variable: "kibana_port"
      label: "Kibana Port"
      description: "Unique public port for Kibana UI"
      type: "int"
      default: 5601
      required: true
elassandra-seed:
  scale: 1
  retain_ip: true
  health_check:
    port: 9042
    interval: 2000
    initializing_timeout: 3600000
    unhealthy_threshold: 5
    strategy: recreate
    response_timeout: 2000
elassandra-node1:
  scale: 1
  retain_ip: true
  health_check:
    port: 9042
    interval: 2000
    initializing_timeout: 3600000
    unhealthy_threshold: 5
    strategy: recreate
    response_timeout: 2000
elassandra-node2:
  scale: 1
  retain_ip: true
  health_check:
    port: 9042
    interval: 2000
    initializing_timeout: 3600000
    unhealthy_threshold: 5
    strategy: recreate
    response_timeout: 2000
