name: homer
version: 5.9.0-TICK
appVersion: 5.9.0
description: Open-Source VoIP and RTC Monitoring
keywords:
- homer
- voip
- rtc
- monitoring
- troubleshooting
- capture
- alerting
home: https://sipcapture.org
icon: http://sipcapture.org/images/logos/preloader-logo.png
sources:
- https://github.com/sipcapture/homer
maintainers:
- name: QXIP
  email: info@qxip.net
engine: gotpl
