apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: caddy
    name: caddy
  spec:
    ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9093"
      port: 9093
      targetPort: 9093
    - name: "9080"
      port: 9080
      targetPort: 9080
    selector:
      io.kompose.service: caddy
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: heplify-server
    name: heplify-server
  spec:
    ports:
    - name: "9060"
      port: 9060
      targetPort: 9060
    - name: 9060-udp
      port: 9060
      protocol: UDP
      targetPort: 9060
    selector:
      io.kompose.service: heplify-server
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telegraf
    name: telegraf
  spec:
    ports:
    - name: "8092"
      port: 8092
      protocol: UDP
      targetPort: 8092
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
    selector:
      io.kompose.service: telegraf
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: caddy
    name: caddy
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: caddy
      spec:
        containers:
        - env:
          - name: ADMIN_PASSWORD
            value: admin
          - name: ADMIN_USER
            value: admin
          image: stefanprodan/caddy
          name: caddy
          ports:
          - containerPort: 3000
          - containerPort: 9090
          - containerPort: 9093
          - containerPort: 9080
          resources: {}
          volumeMounts:
           - name: caddy-config-volume
             mountPath: /etc/caddy
        restartPolicy: Always
        volumes:
          - name: caddy-config-volume
            configMap:
              name: homer-caddy-config
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: chronograf
    name: chronograf
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: chronograf
      spec:
        containers:
        - env:
          - name: INFLUXDB_URL
            value: http://influxdb:8086
          - name: KAPACITOR_URL
            value: http://kapacitor:9092
          image: chronograf:1.5-alpine
          name: chronograf
          resources: {}
          volumeMounts:
           - name: telegraf-config-volume
             mountPath: /etc/telegraf
        volumes:
          - name: telegraf-config-volume
            configMap:
              name: homer-telegraf-config
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
      spec:
        containers:
        - env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_ROOT_HOST
            value: '%'
          - name: MYSQL_ROOT_PASSWORD
          image: mariadb:latest
          name: db
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
      org.label-schema.group: monitoring
    creationTimestamp: null
    labels:
      io.kompose.service: heplify-server
    name: heplify-server
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: heplify-server
      spec:
        containers:
        - args:
          - ./heplify-server
          env:
          - name: HEPLIFYSERVER_DBADDR
            value: db:3306
          - name: HEPLIFYSERVER_DBDRIVER
            value: mysql
          - name: HEPLIFYSERVER_DBPASS
          - name: HEPLIFYSERVER_DBUSER
            value: root
          - name: HEPLIFYSERVER_HEPADDR
            value: 0.0.0.0:9060
          - name: HEPLIFYSERVER_LOGLVL
            value: info
          - name: HEPLIFYSERVER_LOGSTD
            value: "true"
          - name: HEPLIFYSERVER_PROMADDR
            value: 0.0.0.0:9096
          - name: HEPLIFYSERVER_PROMTARGETIP
          - name: HEPLIFYSERVER_PROMTARGETNAME
          image: negbie/heplify-server:latest
          name: heplify-server
          ports:
          - containerPort: 9060
          - containerPort: 9060
            protocol: UDP
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: homer-webapp
    name: homer-webapp
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: homer-webapp
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: db
          - name: DB_PASS
          - name: DB_USER
            value: root
          image: sipcapture/homer-webapp
          name: homer-webapp
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: influxdb
    name: influxdb
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: influxdb
      spec:
        containers:
        - image: influxdb:1.5-alpine
          name: influxdb
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influx-data
        restartPolicy: Always
        volumes:
        - name: influx-data
          persistentVolumeClaim:
            claimName: influx-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: influx-data
    name: influx-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: kapacitor
    name: kapacitor
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: kapacitor
      spec:
        containers:
        - env:
          - name: KAPACITOR_HOSTNAME
            value: kapacitor
          - name: KAPACITOR_INFLUXDB_0_URLS_0
            value: http://influxdb:8086
          image: kapacitor:1.5-alpine
          name: kapacitor
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o homer.yaml
      kompose.version: 1.13.0 (84fa826)
    creationTimestamp: null
    labels:
      io.kompose.service: telegraf
    name: telegraf
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: telegraf
      spec:
        containers:
        - image: telegraf:1.5-alpine
          name: telegraf
          ports:
          - containerPort: 8092
            protocol: UDP
          - containerPort: 8125
            protocol: UDP
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

