.catalog:
  name: "Homer"
  version: "5.0.5-AllInOne (Debian/Kamailio 4)"
  description: "Homer: VoIP Monitoring & Capture"
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for WebApp"
      type: "int"
      default: 80
      required: true
    - variable: "hep_port"
      label: "Public HEP Port"
      description: "Unique public HEP port for Kamailio"
      type: "int"
      default: 9060
      required: true
