.catalog:
  name: Cassandra
  version: 0.1.0-rancher1
  description: |
    (Experimental) Apache Cassandra Node
  minimum_rancher_version: v1.0.0
  maintainer: "Lorenzo Mangani <lorenzo.mangani@gmail.com>"
  uuid: cassandra-0
  questions:
    - variable: "cluster_name"
      description: "Cluster to participate in (no spaces)"
      label: "Cluster Name:"
      required: true
      default: "cluster01"
      type: "string"
    - variable: "num_tokens"
      description: "Number of Tokens to Use in Cluster Sharding. 16-64 Recommended"
      label: "Number of Tokens:"
      required: true
      default: 16 
      type: "int"

cassandra:
  scale: 1
  retain_ip: true
  health_check:
    port: 9042
    interval: 2000
    initializing_timeout: 3600000
    unhealthy_threshold: 5
    strategy: recreate
    response_timeout: 2000
