.catalog:
  name: "ElasticFence"
  version: "2.4.1-rancher1"
  description: "Elasticsearch 2.4.1 + Fence + Kibi 4.5"
  maintainer: "Lorenzo Mangani <lorenzo.mangani@gmail.com>"
  uuid: elasticfence-2
  questions:
    - variable: "cluster_name"
      description: "Cluster to participate in (no spaces)"
      label: "Cluster Name:"
      required: true
      default: "cluster01"
      type: "string"
    - variable: "public_port"
      label: "ES Public Port"
      description: "Unique public port for ES API"
      type: "int"
      default: 9200
      required: true
    - variable: "kibi_port"
      label: "Kibi Public Port"
      description: "Unique public port for Kibi"
      type: "int"
      default: 5606
      required: true
elasticfence:
  scale: 1
  retain_ip: false
